{
  homebrew.casks = [
    "audacity"
    "chatgpt"
    "claude"
    "figma"
    "gdlauncher"
    "microsoft-excel"
    "microsoft-onenote"
    "microsoft-powerpoint"
    "microsoft-word"
    "moonlight"
    "nextcloud"
    "onedrive"
    "parsec"
    "playcover-community"
    "vlc"
    "zoom"
  ];
}
